name: Build and Deploy IPK Center

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          # 强制安装 ipkg-utils 并验证
          sudo apt-get update -y
          sudo apt-get install -y ipkg-utils
          which ipkg-make-index || { echo "ipkg-make-index not found!"; exit 1; }
          
          python -m pip install --upgrade pip
          pip install requests

      - name: Prepare directories
        run: |
          mkdir -p archive dist/opkg
          ls -la

      - name: Run sync script
        run: python main.py

      - name: Verify artifacts
        run: |
          ls -la ./dist
          ls -la ./dist/opkg
          [ -f ./dist/.nojekyll ] || { echo ".nojekyll missing!"; exit 1; }

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true











