name: Build and Deploy IPK Center

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          # 从OpenWrt官方源安装正确版本的ipkg-utils
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://downloads.openwrt.org/releases/22.03.0/targets/x86/64/packages/Packages.gz
          gunzip Packages.gz
          package_url=$(grep -A 10 "Package: ipkg-utils" Packages | grep "Filename:" | cut -d' ' -f2)
          wget https://downloads.openwrt.org/releases/22.03.0/targets/x86/64/packages/${package_url}
          sudo dpkg -i --force-depends ipkg-utils_*_x86_64.ipk
          
          python -m pip install --upgrade pip
          pip install requests

      - name: Prepare directories
        run: |
          mkdir -p archive dist/opkg
          ls -la

      - name: Run sync script
        run: python main.py

      - name: Verify artifacts
        run: |
          ls -la ./dist
          [ -f ./dist/.nojekyll ] || { echo ".nojekyll missing!"; exit 1; }

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true











