name: Build and Deploy IPK Center

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          sudo apt-get update
          sudo apt-get install -y ipkg-utils  # 修复关键错误：安装ipkg-make-index

      - name: Run sync script
        run: |
          mkdir -p archive dist/opkg  # 确保目录存在
          python main.py

      - name: List generated files
        run: |
          ls -la ./dist
          ls -la ./dist/opkg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: false
          force_orphan: true











