name: center OpenWrt IPK Packages

on:
  schedule:
    - cron: '0 2 */7 * *'  # 每7天（UTC 2:00，约北京时间上午10:00）自动运行
  workflow_dispatch:       # 支持手动触发运行

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq wget

      - name: Run sync script
        run: bash scripts/main.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-ipk-center-output
          path: output/

