name: Build and Deploy IPK Center

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          sudo apt-get update && sudo apt-get install -y gzip  # 安装 gzip
          gzip --version  # 确认 gzip 安装成功

      - name: Run sync script
        run: |
          echo "Starting sync script"
          python main.py

      - name: List docs directory
        run: ls -la ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          exclude: ''












