name: Build and Deploy IPK Center

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          sudo apt-get update
          sudo apt-get install -y gzip  # 安装 gzip
          which gzip  # 确认 gzip 安装路径
          gzip --version  # 确认 gzip 版本

      - name: Check gzip installation
        run: |
          echo "Checking gzip availability..."
          if ! command -v gzip &> /dev/null; then
            echo "gzip could not be found, exiting."
            exit 1
          else
            echo "gzip is available."
          fi

      - name: Run sync script
        run: |
          echo "Starting sync script"
          python main.py

      - name: Debug directory and files
        run: |
          echo "Current directory:"
          pwd
          echo "List of files in the current directory:"
          ls -la

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          exclude: ''














