name: Build and Deploy IPK Center

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Install ipkg-make-index
        run: |
          mkdir -p ~/ipkg-tools
          curl -Lo ~/ipkg-tools/ipkg-make-index.sh https://raw.githubusercontent.com/openwrt/openwrt/master/scripts/ipkg/ipkg-make-index.sh
          chmod +x ~/ipkg-tools/ipkg-make-index.sh
          sudo ln -sf ~/ipkg-tools/ipkg-make-index.sh /usr/local/bin/ipkg-make-index

      - name: Verify ipkg-make-index
        run: ipkg-make-index --help

      - name: Run sync script
        run: python main.py

      - name: Prepare publish directory
        run: |
          mkdir publish
          cp -r archive opkg index.html .nojekyll publish/

      - name: List publish directory
        run: ls -la ./publish

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish

